[build]
  publish = "."

# If you use client-side routing, keep this redirect enabled.
# If not, it is still safe: Netlify serves static files before applying redirects.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
